version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=eventosapp
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-compose-network

volumes:
  db:

networks:
  mysql-compose-network:
    driver: bridge
